### ISSUE TITLE
Comparison with power-shell

### ISSUE THREAD

**Issue by elazarl** [ilyash/ngs#14]
This sounds like there's an overlap with powershell.

Would be happy for a comparison in the README file.

**Comment by zglozman** [comment]
Elazar, I dont think this is a proper comparison.  The core value of the NGS is working with a variety of cli/restful apis, that are JSON based. While all modern scripting languages, are sort of similar, NGS is focused on that, as well as simultaneous execution of tasks through the pmap interface. please checkout the examples provided, and it all should be pretty clear by then. 

Z

**Comment by elazarl** [comment]
Powershell is not a scripting language. It's a shell, just like bash, which
enables you to work with a veriety of c/restul APIs. Look at chocolatey for
REST API usage example.

Also, it sends structured, JSON-like information, and not just text,
similar to what you've had in mind.

If you compare to the fish shell, I think a comparison to Powershell would
be in place, and would help the reader.

**Comment by zglozman** [comment]
Take a look at how we just used ngs to box test a set of command line interfaces: https://github.com/beameio/beame-sdk/blob/106b8fadf9ca923bc934a083e82f714dedf67204/tests/cli_tests/testAll.ngs

**Comment by elazarl** [comment]
Why is the term "shell" mentioned. cucumber-like testing framework for rest
APIs is nothing like shell.

I'm afraid I'm having trouble understanding the essence of the project,
even after reading your example.

**Comment by ilyash** [comment]
@zglozman meant to show how concise and convenient NGS is (compared to PowerShell and other shells), not what it is for. I have added the comparison in readme. I'll probably have more insights along the way. If I do, I'll extend the comparison section.
