### ISSUE TITLE
implementation language

### ISSUE THREAD

**Issue by fcantournet** [ilyash/ngs#3]
Since you're starting fresh I must ask : why C ?

Wouldn't this benefit from being written in rust, if only for security considerations.

Reading the current design ideas, it seems you'll want to implement some form of functionnal "code" language in the shell. Might be quite useful to do this in a language that has the required primitives.

**Comment by ilyash** [comment]
I see why it makes sense. Here is the history behind the choice of C:

**First (partial) implementation** was in JavaScript. I knew it was a throw-away implementation as it was first attempt. Chances to do something like this right on first attempt are not great. The NGS language does not need to be particularly fast but JS was really slow (or, more correctly my implementation in JS :) ).

**Second (partial) implementation** was in Lisp (SBCL implementation of it). The thought was simple: I compile to Lisp and it compiles to machine code and runs it. I have hit two walls:

1. The compilation phase was slow. I mean you hit enter and you see the delay (maybe 0.2 or 0.3 seconds).
2. Could not get source tracking (to show source locations in exceptions backtrace) that wouldn't waste about half of CPU time.

In addition, I was not very familiar with the language and it slowed me down.

**Third (in development) implementation** I decided to have in a language that

1. I will not get stuck with, unable to solve a problem.
2. Will have other languages implemented in it so I could look at the implementations (Python, Ruby, Bash, Perl). This is important as I don't have experience in creating languages.
3. I have to know the language (which rules out Rust and Go for example).

... and that was C.

P.S.
You can take a look at first two implementations. They are in this repository, just check out old enough commit.
