### ISSUE TITLE
Consider AGPL for the license

### ISSUE THREAD

**Issue by ahungry** [ilyash/ngs#4]
I see you chose GPL, which I'm a big fan of, however it looks like this is meant to run through a web browser? 

If that's the case, with GPL someone can use the SaaS loophole to provide an implementation of this shell, while avoiding the copyleft protection GPL provides.  AGPL works to fix that loophole.

**Comment by ilyash** [comment]
Really not sure about this.

First, http://www.theregister.co.uk/2011/03/31/google_on_open_source_licenses/

Second, I don't really see system engineers (primary target audience) using shell as a service :)

Let's wait with this a bit. Meanwhile, I encourage people to post here pros and cons.

**Comment by ilyash** [comment]
Closing because of absence of any comments in a week. Please reopen if there are any additional thoughts.
