### ISSUE TITLE
Roadmap/Guide/Tasks/TODO

### ISSUE THREAD

**Issue by 7rin0** [ilyash/ngs#5]
Some kind of roadmap or even a draft will be a very good guide to contributors, don't you think? :)

**Comment by ilyash** [comment]
Sure!
Following the HN publication which was a surprise to me and following interest, I have started with publishing [my internal todo](https://github.com/ilyash/ngs/blob/master/c/todo.txt). Let's discuss here further steps. Probably make it clear should be the first :)

**Comment by ilyash** [comment]
I have updated [the todo file](https://github.com/ilyash/ngs/blob/master/c/todo.txt). Feedback is welcome as I guess there will be things that are clear to me which are not necessary clear for everyone else.

**Comment by ilyash** [comment]
No reply for a day + probably fixed. Closing. Please re-open if needed.
