### ISSUE TITLE
I like your project! Have a look at my old 'linuxml' project for ideas maybe ...

### ISSUE THREAD

**Issue by birchb1024** [ilyash/ngs#7]
[Archived  here (link)](http://web.archive.org/web/20050211082831/http://www.geocities.com/ResearchTriangle/Forum/6751/)

**Comment by ilyash** [comment]
I agree with the thoughts behind your project. I prefer JSON. I was toying with similar ideas. Some of them will probably make it to NGS (as you can see in readme, I'm all for semantic data instead of text).

Why is your project archived?

**Comment by ilyash** [comment]
Thanks!
