### ISSUE TITLE
Syntax feedback

### ISSUE THREAD

**Issue by nikolay** [ilyash/ngs#8]
* The choice of `F` is **very** weird! Can't you use lowercase `fn` instead?
* At the same time, you've got `callable:Fun` -  please, make it consistent, and use `fn` and `callable:Fn`!
* Although `local` is familiar, the language is so vastly different than Bash that the shorter `let` would be much better!

**Comment by ilyash** [comment]
Thanks! I'll be thinking about your points.

The reasons behind current syntax:

`F` - the language has functional aspects, so function declaration is common and hence should be short. For short callbacks, for example `a.map(F(x) x+1)` , the overhead should be kept small small.

`Fun` - tried to keep all types to be 3-4 letters

`local` seems to convey the best the meaning of declaration

**Comment by nikolay** [comment]
So, you try to save from `fn` and `func`, but don't want to save characters from `local`? Inconsistent reasoning, I'd say. Honestly, I see your point about `F`, but it's confusing. In math, at least, it's `f` for a function, and the capital letter pokes eyes! Although I have some new languages adopting `fun` over `fn` and `func`, it's still wound be better to use `fun` and be consistent with the type than a capital `F`.

**Comment by ilyash** [comment]
For the syntax the main rule is that the more frequent something is the shorter it should be. `F` is much more common than `local`.

I have doubts regarding the `F`, `fn` and `fun` naming. Needs more thought.

I was thinking about the `F` / `Fun` inconsistency. I'm not sure how much effort it would be to use the same keyword. `F() ...` means a declaration. Name of a type when used as `TypeName()` is a constructor for that type. There is a potential problem with that.

**Comment by nikolay** [comment]
Well, statistically, I use `local` in Bash a lot more often than function declarations, bu in the case of NGS, it's a slightly different story as NGS is a more FP than Bash, but, `F` is not readable. 

More language developers should take tips from Rust, which **everybody** loves - simple, predictable, and consistent syntax - no weird stuff, no need to consult with documentation all the time.

Yes, if you're gonna abbreviate to the max, abbreviate **all** identifiers and keywords - don't cherry-pick, don't let people memorize that it's `local`, not `loc`, but it's `Fun` and not `Function`!

**Consistency is everything!**

**Comment by ilyash** [comment]
Thanks for your input. I'm still not sure what would be the best option. I'll keep thinking about this.
