### ISSUE TITLE
make fails?

### ISSUE THREAD

**Issue by Wingie** [ilyash/ngs#9]
gcc -c -Wall -Wextra -gdwarf-4 -g3 -g -O1 vm.c -o vm.o
vm.c: In function ‘native_attr_pthreadattr’:
vm.c:1021:33: error: expected ‘)’ before ‘restrict’
 #define ATTR ((pthread_attr_t * restrict)&GET_PTHREADATTR(argv[0]))
                                 ^
vm.c:1025:28: note: in expansion of macro ‘ATTR’
   pthread_attr_get ## name(ATTR, &i); \
                            ^
vm.c:1041:2: note: in expansion of macro ‘INT_ATTR’
  INT_ATTR (detachstate);
  ^
vm.c:1021:33: error: expected ‘)’ before ‘restrict’
 #define ATTR ((pthread_attr_t * restrict)&GET_PTHREADATTR(argv[0]))
                                 ^
vm.c:1030:28: note: in expansion of macro ‘ATTR’
   pthread_attr_get ## name(ATTR, &size); \
                            ^
vm.c:1042:2: note: in expansion of macro ‘SIZE_ATTR’
  SIZE_ATTR(guardsize);
  ^
vm.c:1021:33: error: expected ‘)’ before ‘restrict’
 #define ATTR ((pthread_attr_t * restrict)&GET_PTHREADATTR(argv[0]))
                                 ^
vm.c:1025:28: note: in expansion of macro ‘ATTR’
   pthread_attr_get ## name(ATTR, &i); \
                            ^
vm.c:1043:2: note: in expansion of macro ‘INT_ATTR’
  INT_ATTR (inheritsched);
  ^
vm.c:1021:33: error: expected ‘)’ before ‘restrict’
 #define ATTR ((pthread_attr_t * restrict)&GET_PTHREADATTR(argv[0]))
                                 ^
vm.c:1025:28: note: in expansion of macro ‘ATTR’
   pthread_attr_get ## name(ATTR, &i); \
                            ^
vm.c:1044:2: note: in expansion of macro ‘INT_ATTR’
  INT_ATTR (scope);
  ^
vm.c:1021:33: error: expected ‘)’ before ‘restrict’
 #define ATTR ((pthread_attr_t * restrict)&GET_PTHREADATTR(argv[0]))
                                 ^
vm.c:1030:28: note: in expansion of macro ‘ATTR’
   pthread_attr_get ## name(ATTR, &size); \
                            ^
vm.c:1045:2: note: in expansion of macro ‘SIZE_ATTR’
  SIZE_ATTR(stacksize);
  ^
vm.c: In function ‘vm_init’:
vm.c:1553:11: error: ‘ffi_type_complex_float’ undeclared (first use in this function)
  FFI_TYPE(ffi_type_complex_float);
           ^
vm.c:1536:33: note: in definition of macro ‘FFI_TYPE’
  vm->c_ ## name = make_ffi_type(name); \
                                 ^
vm.c:1553:11: note: each undeclared identifier is reported only once for each function it appears in
  FFI_TYPE(ffi_type_complex_float);
           ^
vm.c:1536:33: note: in definition of macro ‘FFI_TYPE’
  vm->c_ ## name = make_ffi_type(name); \
                                 ^
vm.c:1554:11: error: ‘ffi_type_complex_double’ undeclared (first use in this function)
  FFI_TYPE(ffi_type_complex_double);
           ^
vm.c:1536:33: note: in definition of macro ‘FFI_TYPE’
  vm->c_ ## name = make_ffi_type(name); \
                                 ^
vm.c:1555:11: error: ‘ffi_type_complex_longdouble’ undeclared (first use in this function)
  FFI_TYPE(ffi_type_complex_longdouble);
           ^
vm.c:1536:33: note: in definition of macro ‘FFI_TYPE’
  vm->c_ ## name = make_ffi_type(name); \
                                 ^
make: *** [vm.o] Error 1

**Comment by ilyash** [comment]
Not sure. I'll dive into this later. Myabe it's gcc version? Which version do you use? I'm using `gcc (Debian 5.3.1-20) 5.3.1 20160519`

**Comment by ilyash** [comment]
Yep. Got this with gcc-4.8 and gcc-4.9 . gcc-5 went fine.

**Comment by Wingie** [comment]
im using gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
let me try and upgrade it.

**Comment by ilyash** [comment]
`Debian clang version 3.6.2-3 (tags/RELEASE_362/final) (based on LLVM 3.6.2)` is also fine. You might want to `make CC=clang`

**Comment by ilyash** [comment]
I've made some fixes and compiled successfully on Ubuntu 14.04 . Please let me know if it works for you too.

**Comment by Wingie** [comment]
Oh yes. this works now!
thanks. :+1:
